from mxdev import Hook
from mxdev import State

import logging


logger = logging.getLogger(__name__)
CHECKOUTS_FILE = "checkouts.cfg"


class WriteBuildoutVersionsExtension(Hook):
    namespace = "plone.releaser"

    def write(self, state: State) -> None:
        """Gets executed after mxdev write operation."""
        checkouts = ""
        versions = ""
        # Note: the names and paths are all lower case,
        # e.g. src/products.cmfplone.
        for name, info in state.configuration.packages.items():
            checkouts += f"    {info['path']}\n"
            versions += f"{name} =\n"
        checkouts_config = f"""# generated by mxdev.ini and plone.releaser
[buildout]
develop =
{checkouts}
[versions]
{versions}"""

        with open(CHECKOUTS_FILE, "w") as myfile:
            myfile.write(checkouts_config)
        logger.info(f"Wrote {CHECKOUTS_FILE}.")
